### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-r8m19#5]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Zoronium** [comment]
before the changes
![image](https://user-images.githubusercontent.com/89680252/182221008-9f813262-3076-416f-965d-08a0a48e1e31.png)
![image](https://user-images.githubusercontent.com/89680252/182223112-9dccb7ec-4aad-4395-946f-58c850a560b8.png)

after Changes 
![image](https://user-images.githubusercontent.com/89680252/182228173-845e55e8-d606-4064-b723-f9e59846aecc.png)
![image](https://user-images.githubusercontent.com/89680252/182223092-977b16a2-16e2-4695-9f77-cb01e8dcd05d.png)

- [x] added placeholder images

**Comment by Zoronium** [comment]
done with #9
